device: cuda:0
input_dim: 4096
use_temperature: true 
unmask_y: True
use_gating_network: true

model_builder:
  _target_: ${model.resolve_model_target}
  concept_encoder:
    _target_: src.models.reward_models.MLP
    input_dim: ${model.input_dim}
    output_dim: null  # placeholder
    hidden_dim: 512
    num_layers: 1
  gating_network_or_scalarizer: ??? 

