model:
  device: cuda:0 
  input_dim: 4096
model_type: 'probabilistic' # 'probabilistic'  or 'deterministic'

training:
  num_epochs: 1
  lr: 1e-4
  eval_steps: 100
  max_num_eval_steps: 10
  seed: 42
  dry_run: False         # Set to true to skip wandb logging and saving
  num_episodes: 100
  acquisition_function: expected_information_gain #'uniform' or 'expected_information_gain'
  num_acquired_samples: 1024
  num_initial_samples: 2048
  keep_ratio: 0.2 # Replay buffer for active learning

loss:
  beta_concept: 1.0              # Weight for concept_loss in total loss
  beta_kl: 0.001

save:
  project_name: active_pref_learning
  wandb_entity: interp_rewards_RLHF
  run_name_prefix: active_learning_crm

data:
  embeddings_path: './datasets/ultrafeedback/embeddings/meta-llama/Meta-Llama-3-8B/'
  splits_path: './datasets/ultrafeedback/splits.csv'
  concept_labels_path: './datasets/ultrafeedback/concept_labels/openbmb' 
  preference_labels_path: './datasets/ultrafeedback/preference_labels/openbmb_average'
  batch_size: 512
 
resolve_model_target:
  deterministic: src.models.reward_models.BottleneckRewardModel
  probabilistic: src.models.reward_models.ProbabilisticBottleneckRewardModel
model_builder:
  _target_: ${resolve_model_target.${model_type}}
  concept_encoder:
    _target_: src.models.reward_models.MLP
    input_dim: ${model.input_dim}
    output_dim: null  # placeholder
    hidden_dim: 512
    num_layers: 1
  gating_network:
    _target_: src.models.reward_models.GatingNetwork
    input_dim: ${model.input_dim}
    output_dim: null  # placeholder
  concept_sampler: gaussian  # only used if model_type is probabilistic

train_dataset:
  _target_: src.data.dataloaders.ExpandableConceptPreferenceDataset
  embeddings_path: ${data.embeddings_path}
  splits_path: ${data.splits_path}
  concept_labels_path: ${data.concept_labels_path}
  preference_labels_path: ${data.preference_labels_path}
  split: train
  num_initial_samples: ${training.num_initial_samples}

val_dataloader:
  _target_: src.data.dataloaders.get_dataloader
  cfg: ${data}
  split: val

