model:
  model_type: probabilistic
  encoder_num_layers: 1
  encoder_hidden_dim: 512
  concept_sampler: gaussian
  input_dim: 4096        
  device: cuda:0           

training:
  num_epochs: 10
  lr: 1e-4
  eval_steps: 100
  max_num_eval_steps: 100
  seed: 0
  dry_run: False         # Set to true to skip wandb logging and saving

loss:
  beta_concept: 1.0              # Weight for concept loss in total loss
  beta_kl: 0.001  

save:
  project_name: active_pref_learning
  run_name_prefix: probabilistic_crm

data:
  embeddings_path: './datasets/ultrafeedback/embeddings/meta-llama/Meta-Llama-3-8B/'
  splits_path: './datasets/ultrafeedback/splits.csv'
  concept_labels_path: './datasets/ultrafeedback/concept_labels/openbmb' 
  preference_labels_path: './datasets/ultrafeedback/preference_labels/openbmb_average'
  batch_size: 1024
  
